---
- name: Deploy Mirage Windows Server
  hosts: windowsServer
  gather_facts: no
  roles:
    - windows
  tags:
    - deploy
    - windows
    - windowsServer

- name: Deploy Mirage Windows Client
  hosts: windowsClient
  gather_facts: no
  roles:
    - windows
  tags:
    - deploy
    - windows
    - windowsClient

- name: Deploy Mirage Linux
  hosts: linux
  become: yes
  roles:
    - linux
  tags:
    - deploy
    - linux

# Currently Under Development, will be added in a future release
# - name: Deploy Mirage FreeBSD/pfSense
#   hosts: freebsd
#   become: yes
#   roles:
#     - freebsd
#   tags:
#     - deploy
#     - freebsd
#     - pfsense

- name: Deploy Puzzler Extension
  hosts: windowsServer:windowsClient
  gather_facts: no
  roles:
    - puzzler
  tags:
    - deploy
    - puzzler