---
- name: Undeploy Mirage Windows Server
  hosts: windowsServer
  gather_facts: no
  vars:
    mirage_action: undeploy
  roles:
    - windows
  tags:
    - undeploy
    - windows
    - windowsServer
    - never

- name: Undeploy Mirage Windows Client
  hosts: windowsClient
  gather_facts: no
  vars:
    mirage_action: undeploy
  roles:
    - windows
  tags:
    - undeploy
    - windows
    - windowsClient
    - never

- name: Undeploy Mirage Linux
  hosts: linux
  become: yes
  vars:
    mirage_action: undeploy
  roles:
    - linux
  tags:
    - undeploy
    - linux
    - never

- name: Undeploy Mirage FreeBSD
  hosts: freebsd
  become: yes
  vars:
    mirage_action: undeploy
  roles:
    - freebsd
  tags:
    - undeploy
    - freebsd
    - pfsense
    - never

- name: Undeploy Puzzler Extension
  hosts: windowsServer:windowsClient
  gather_facts: no
  vars:
    mirage_action: undeploy
  roles:
    - puzzler
  tags:
    - undeploy
    - puzzler
    - never